"use strict";var Core=Core||{};Core.Agent=Core.Agent||{};Core.Agent.TicketAction=(function(TargetNS){function SerializeData(Data){var QueryString='';$.each(Data,function(Key,Value){QueryString+=';'+encodeURIComponent(Key)+'='+encodeURIComponent(Value);});return QueryString;}
function OpenSpellChecker(){var SpellCheckIFrame,SpellCheckIFrameURL;SpellCheckIFrameURL=Core.Config.Get('CGIHandle')+'?Action=AgentSpelling;Field=RichText;Body='+encodeURIComponent($('#RichText').val());SpellCheckIFrameURL+=SerializeData(Core.App.GetSessionInformation());SpellCheckIFrame='<iframe class="TextOption SpellCheck" src="'+SpellCheckIFrameURL+'"></iframe>';Core.UI.Dialog.ShowContentDialog(SpellCheckIFrame,'','10px','Center',true);}
function OpenAddressBook(){var AddressBookIFrameURL,AddressBookIFrame;AddressBookIFrameURL=Core.Config.Get('CGIHandle')+
'?Action=AgentBook;ToCustomer='+encodeURIComponent($('#CustomerAutoComplete, #ToCustomer').val())+
';CcCustomer='+encodeURIComponent($('#Cc, #CcCustomer').val())+
';BccCustomer='+encodeURIComponent($('#Bcc, #BccCustomer').val());AddressBookIFrameURL+=SerializeData(Core.App.GetSessionInformation());AddressBookIFrame='<iframe class="TextOption" src="'+AddressBookIFrameURL+'"></iframe>';Core.UI.Dialog.ShowContentDialog(AddressBookIFrame,'','10px','Center',true);}
function OpenCustomerDialog(){var CustomerIFrameURL,CustomerIFrame;CustomerIFrameURL=Core.Config.Get('CGIHandle')+'?Action=AdminCustomerUser;Nav=None;Subject=;What=';CustomerIFrameURL+=SerializeData(Core.App.GetSessionInformation());CustomerIFrame='<iframe class="TextOption Customer" src="'+CustomerIFrameURL+'"></iframe>';Core.UI.Dialog.ShowContentDialog(CustomerIFrame,'','10px','Center',true);}
function AddMailAddress($Link){var $Element=$('#'+$Link.attr('rel')),NewValue=$Element.val(),NewData,NewDataItem,Length;if(NewValue.length){NewValue=NewValue+', ';}
NewValue=NewValue+
Core.Data.Get($Link.closest('tr'),'Email')
.replace(/&quot;/g,'"')
.replace(/&lt;/g,'<')
.replace(/&gt;/g,'>');$Element.val(NewValue);Length=$Element.val().length;$Element.focus();$Element[0].setSelectionRange(Length,Length);if($Link.attr('rel')==='ToCustomer'&&Core.Config.Get('CustomerInfoSet')){NewData=$('#CustomerData').val();NewDataItem=Core.Data.Get($Link.closest('a'),'customerdatajson');if(NewData){NewData=Core.JSON.Parse(NewData);$.each(NewDataItem,function(CustomerMail,CustomerKey){NewData[CustomerMail]=CustomerKey;});$('#CustomerData').val(Core.JSON.Stringify(NewData));}
else
{$('#CustomerData').val(Core.JSON.Stringify(NewDataItem));}}}
function MarkPrimaryCustomer(){$('.CustomerContainer').children('div').each(function(){var $InputObj=$(this).find('.CustomerTicketText'),$RadioObj=$(this).find('.CustomerTicketRadio');if($RadioObj.prop('checked')){$InputObj.addClass('MainCustomer');}
else{$InputObj.removeClass('MainCustomer');}});}
TargetNS.Init=function(){$('#OptionSpellCheck').bind('click',function(){OpenSpellChecker();return false;});$('#OptionAddressBook').bind('click',function(){OpenAddressBook();return false;});$('#OptionCustomer').bind('click',function(){OpenCustomerDialog();return false;});if(parseInt(Core.Config.Get('SpellChecker'),10)===1&&parseInt(Core.Config.Get('NeedSpellCheck'),10)===1){Core.Config.Set('TextIsSpellChecked',false);$('#RichTextField, .RichTextField').on('click','.cke_button__spellcheck',function(){Core.Config.Set('TextIsSpellChecked',true);});$('#OptionSpellCheck').bind('click',function(){Core.Config.Set('TextIsSpellChecked',true);});if(parseInt(Core.Config.Get('RichTextSet'),10)===0){$('#RichTextField, .RichTextField').on('change','#RichText',function(){Core.Config.Set('TextIsSpellChecked',false);});}
Core.Form.Validate.SetSubmitFunction($('form[name=compose]'),function(){if($('#RichText').val()&&!$('#RichText').hasClass('ValidationIgnore')&&!Core.Config.Get('TextIsSpellChecked')){Core.App.Publish('Event.Agent.TicketAction.NeedSpellCheck',[$('#RichText')]);Core.UI.Dialog.ShowContentDialog('<p>'+Core.Config.Get('SpellCheckNeededMsg')+'</p>','','150px','Center',true,[{Label:'<span>'+Core.Config.Get('DialogCloseMsg')+'</span>',Function:function(){Core.UI.Dialog.CloseDialog($('.Dialog:visible'));Core.Form.EnableForm($('#RichText').closest('form'));},Class:'Primary'}]);return false;}
$('#RichText').closest('form').get(0).submit();});}
MarkPrimaryCustomer();Core.App.Subscribe('Event.Agent.CustomerSearch.GetCustomerInfo.Callback',function(){MarkPrimaryCustomer();});$('#submitRichText').on('click',function(Event){var ToCustomer=$('#ToCustomer').val()||'',CcCustomer=$('#CcCustomer').val()||'',BccCustomer=$('#BccCustomer').val()||'',FromCustomer=$('#FromCustomer').val()||'';if(ToCustomer.length||CcCustomer.length||BccCustomer.length||FromCustomer.length){window.setTimeout(function(){$('#submitRichText').trigger('click');},100);Event.preventDefault();Event.stopPropagation();return false;}});Core.App.Subscribe('Event.UI.ToggleWidget',function($WidgetElement){if($WidgetElement.attr('id')!=='WidgetArticle'){return;}
if($WidgetElement.hasClass('Expanded')){$('#CreateArticle').prop('checked',true);}});Core.App.Subscribe('Event.Agent.TicketAction.NeedSpellCheck',function($TextElement){var $Widget=$TextElement.closest('div.WidgetSimple');if($Widget.attr('id')!=='WidgetArticle'||$Widget.hasClass('Expanded')){return;}
$Widget.find('div.WidgetAction.Toggle > a').trigger('click');});};TargetNS.InitAddressBook=function(){$('#SearchResult a').bind('click',function(){AddMailAddress($(this));return false;});$('#Apply').bind('click',function(){var $To,$Cc,$Bcc,CustomerData;if($('#CustomerAutoComplete',parent.document).length){$To=$('#CustomerAutoComplete',parent.document);$Cc=$('#Cc',parent.document);$Bcc=$('#Bcc',parent.document);$To.val($('#ToCustomer').val());$Cc.val($('#CcCustomer').val());$Bcc.val($('#BccCustomer').val());}
else{$To=$('#ToCustomer',parent.document);$Cc=$('#CcCustomer',parent.document);$Bcc=$('#BccCustomer',parent.document);if($('#CustomerData').val()){CustomerData=Core.JSON.Parse($('#CustomerData').val());$.each(CustomerData,function(CustomerMail,CustomerKey){$To.val(CustomerMail);parent.Core.Agent.CustomerSearch.AddTicketCustomer('ToCustomer',CustomerMail,CustomerKey);});}
else{$.each($('#ToCustomer').val().split(/, ?/),function(Index,Value){$To.val(Value);parent.Core.Agent.CustomerSearch.AddTicketCustomer('ToCustomer',Value);});}
$.each($('#CcCustomer').val().split(/, ?/),function(Index,Value){$Cc.val(Value);parent.Core.Agent.CustomerSearch.AddTicketCustomer('CcCustomer',Value);});$.each($('#BccCustomer').val().split(/, ?/),function(Index,Value){$Bcc.val(Value);parent.Core.Agent.CustomerSearch.AddTicketCustomer('BccCustomer',Value);});}
parent.Core.UI.Dialog.CloseDialog($('.Dialog',parent.document));});$('#Cancel').bind('click',function(){parent.Core.UI.Dialog.CloseDialog($('.Dialog',parent.document));});};TargetNS.InitSpellCheck=function(){$('#SpellCheck select, #SpellCheck input[type="text"]').bind('change',function(){var $Row=$(this).closest('tr'),RowCount=parseInt($Row.attr('id').replace(/Row/,''),10);$Row.find('input[type="radio"][id=ChangeWord'+RowCount+']').prop('checked',true);});$('#Apply').bind('click',function(){var FieldName=$('#Field').val(),$Body=$('#'+FieldName,parent.document);$Body.val($('#Body').val());parent.Core.UI.Dialog.CloseDialog($('.Dialog',parent.document));});$('#Cancel').bind('click',function(){parent.Core.UI.Dialog.CloseDialog($('.Dialog',parent.document));});};TargetNS.UpdateCustomer=function(Customer){var $UpdateForm=$('form[name=compose]',parent.document);$UpdateForm
.find('#ExpandCustomerName').val('2')
.end()
.find('#PreSelectedCustomerUser').val(Customer)
.end()
.submit();parent.Core.UI.Dialog.CloseDialog($('.Dialog',parent.document));};TargetNS.SelectRadioButton=function(Value,Name){$('input[type="radio"][name='+Name+'][value='+Value+']').prop('checked',true);};TargetNS.ConfirmTemplateOverwrite=function(FieldName,$TemplateSelect,Callback){var Content='',LastValue=$TemplateSelect.data('LastValue')||'';Content=$('#'+FieldName).val();if(typeof CKEDITOR!=='undefined'&&CKEDITOR.instances[FieldName]){Content=CKEDITOR.instances[FieldName].getData();}
if(Content.length&&!window.confirm(Core.Config.Get('TicketActionTemplateOverwrite')+' '+Core.Config.Get('TicketActionTemplateOverwriteConfirm')))
{$TemplateSelect.val(LastValue).trigger('redraw');}
else if($.isFunction(Callback)){Callback();$TemplateSelect.data('LastValue',$TemplateSelect.val());}}
return TargetNS;}(Core.Agent.TicketAction||{}));

